dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- ctest
- ls CMakeFiles/matrix.dir
- ls CMakeFiles/tests.dir
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T codecov-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhankhenshaw:$BINTRAY_API_KEY "https://api.bintray.com/content/hankhenshaw/MidRep/Codecov/$TRAVIS_BUILD_NUMBER/codecov-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"